name: Pull Request Stats

on: pull_request

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: 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
          period: 9999
          charts: true
          disable-links: false
          sort-by: 'COMMENTS'
          limit: 10
